### PR TITLE
allow CANONICAL_DOMAIN_EXEMPT to be a function

### PR DESCRIPTION
**Pull request by PetrDlouhy**
I just realized, that I would like to exempt paths like `api.blenderkit.com/api/v1` but not paths like `api.blenderkit.com/whatever`.

I don't want to complicate this project too much, so I think maybe we could add a function that would get request and return True or False whether we should exempt the path.
Unfortunately I didn't have this idea before.

I implemented it so that `CANONICAL_DOMAIN_EXEMPT` could be both the list as before and also a function. But I could easily transform the code to specialized settings `CANONICAL_DOMAIN_EXEMPT_FUNCTION`.

@matthiask What do you think? Isn't this too much? If you are willing to accept this I will change also the documentation accordingly.

### CODE REVIEW

**Review by matthiask — COMMENTED** [review]
I think that's a very interesting idea and I like it. It's more flexible than what we have now. Thanks for thinking of that.

Maybe you could use `django.utils.module_loading.import_string` and change the default value to to the `SECURE_REDIRECT_EXEMPT` thing? So, when people change it, they can decide whether they want to keep `SECURE_REDIRECT_EXEMPT` or if they want to replace that as well?

`CANONICAL_DOMAIN_EXEMPT = "canonical_domain.utils.secure_redirect_exempt"`

**Comment by PetrDlouhy** [comment]
I am not fully sure what you mean. If you mean that:

- `CANONICAL_DOMAIN_EXEMPT` will remain the same
- there will be `CANONICAL_DOMAIN_EXEMPT_FUNCTION` with default value `"canonical_domain.utils.canonical_domain_exempt"`
- the function will look something like:
```python
def canonical_domain_exempt(request):
    exempt = [re.compile(r) for r in getattr(settings, "CANONICAL_DOMAIN_EXEMPT", [])]
    return any(pattern.search(request.get_host()) for pattern in host_exempt)
```

then I see that it would simplify the code.
I will just have to think how to not throw away the benefit of running `re.compile` at the middleware initialization.



But I am not sure how is this related to `SECURE_REDIRECT_EXEMPT`, which has slightly different condition.

**Comment by matthiask** [comment]
I'm sorry, but sometimes code speaks clearer than words. I have pushed an update to this pull request. I noticed that my idea wasn't expressed clearly and also didn't work, because `SECURE_REDIRECT_EXEMPT` really is a separate thing from `CANONICAL_DOMAIN_EXEMPT`. I hope my proposal works for you, and if not, I'm happy to continue working with you on this (feel free to throw away my work in this case if it helps).

**Comment by PetrDlouhy** [comment]
@matthiask I think this looks very good. Having both function and str seems reasonable.
I am OK with throwing out the list functionality, hope nobody implemented it in the past day.

The only think I would think about is to rename the settings variable to `CANONICAL_DOMAIN_EXEMPT_FUNC` (or `FUNCTION`) to make it clear it is not the same thing as `SECURE_REDIRECT_EXEMPT`.

**Comment by PetrDlouhy** [comment]
BTW, this is good for purpose of testing: `lambda r: re.search(r"^api.example.com$", r.get_host())` but maybe not so good for the purpose of documentation.
The function is executed for every request so performace can matter. I would recommend users to do something like:

```python
url_regexp = re.compile(r"^api\.example\.com$")
CANONICAL_DOMAIN_EXEMPT_FUNC = lambda r: url_regexp.match(r.get_host())
```
But we can add it just to documentation.

**Comment by matthiask** [comment]
Thanks! 

Django also uses `KEY_PREFIX` to refer to something which could be a function in the caching framework; I think the shorter version is fine.

You're right, do you want to submit that as well? By the way, the `re` module does it's own caching of compiled regexes, see https://github.com/python/cpython/blob/2f5c3b09e45798a18d60841d04a165fb062be666/Lib/re/__init__.py#L321-L328; but of course it still makes sense to compile them eagerly.

**Comment by PetrDlouhy** [comment]
@matthiask Thank you very much. Everything seems to be working OK now.

**Comment by matthiask** [comment]
@PetrDlouhy Good to hear! It's been a pleasure.

**Pull request merged**
